[[language]]
name = "rust"

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "day1"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", args = ["1"]}

[language-server.rust-analyzer.config.files]
watcher = "client"

[[language]]
name = "lean"
auto-format = true
formatter = { command = "lucr", args = [] }
