[package]
name = "aoc_macro"
version = "0.3.1"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "^1.0", features = ["full"] }
quote = "^1.0"

[lib]
proc-macro = true
