name = "AoC_Julia"
uuid = "83a32440-6450-4b14-aeff-d72eb91a7b9d"
version = "0.1.0"
authors = ["Narazaki, Shuji <shujinarazaki@protonmail.com>"]

[deps]
AoC = "d3ea9ae9-af4a-410f-a534-06eea3ee9a32"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"

[sources]
AoC = {path = "AoC"}

[compat]
AoC = "0.1.0"
HiGHS = "1.20.1"
IJulia = "1.31.0"
JuMP = "1.29.3"
LanguageServer = "4.5.1"
ParserCombinator = "2.2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
